SET IDENTITY_INSERT [dbo].[Age] ON
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (1, N'35-44')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (2, N'35-44')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (3, N'45-54')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (4, N'40')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (5, N'35-44')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (6, N'35-44')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (7, N'25-34')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (8, N'prefer not to say')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (9, N'prefer not to say')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (10, N'prefer not to say')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (11, N'prefer not to say')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (12, N'55-64')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (13, N'35-44')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (14, N'25-34')
INSERT INTO [dbo].[Age] ([Id], [Age]) VALUES (15, N'25-34')
SET IDENTITY_INSERT [dbo].[Age] OFF
