create table [dbo].[symptoms]
(
[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
[symptom_name] VARCHAR(MAX) NOT NULL
)
GO
insert into symptoms(symptom_name) values('fatigue');
insert into symptoms(symptom_name) values('fever');
insert into symptoms(symptom_name) values('headache');
insert into symptoms(symptom_name) values('dyspnea');
insert into symptoms(symptom_name) values('nausea');
insert into symptoms(symptom_name) values('sinus tachycardia');
insert into symptoms(symptom_name) values('chills');
insert into symptoms(symptom_name) values('diarrhea');
insert into symptoms(symptom_name) values('cough');
insert into symptoms(symptom_name) values('exanthem');
insert into symptoms(symptom_name) values('prolonged exspirium');
insert into symptoms(symptom_name) values('back pain');
insert into symptoms(symptom_name) values('vomit');
insert into symptoms(symptom_name) values('confusion');
insert into symptoms(symptom_name) values('wheezing');
insert into symptoms(symptom_name) values('chronic cough');
insert into symptoms(symptom_name) values('colorectal carcinoma');
insert into symptoms(symptom_name) values('dizziness');
insert into symptoms(symptom_name) values('hypoglycaemia');
insert into symptoms(symptom_name) values('dementia');
insert into symptoms(symptom_name) values('anemia');
insert into symptoms(symptom_name) values('meningism');
insert into symptoms(symptom_name) values('skin tags');
insert into symptoms(symptom_name) values('papilledema');
insert into symptoms(symptom_name) values('emphysema');
insert into symptoms(symptom_name) values('inappetence');
insert into symptoms(symptom_name) values('right bundle branch block');
insert into symptoms(symptom_name) values('skin abscesses');
insert into symptoms(symptom_name) values('haemolytic anemia');
insert into symptoms(symptom_name) values('asthma applicable');
insert into symptoms(symptom_name) values('rattle sound lungs');
insert into symptoms(symptom_name) values('vomiting');
insert into symptoms(symptom_name) values('dysthymia');
insert into symptoms(symptom_name) values('petechial');
insert into symptoms(symptom_name) values('pruritus');
insert into symptoms(symptom_name) values('cyanosis');
insert into symptoms(symptom_name) values('leukocytosis');
insert into symptoms(symptom_name) values('depressive mood');
insert into symptoms(symptom_name) values('anorexia');
insert into symptoms(symptom_name) values('incontinence');
insert into symptoms(symptom_name) values('rash');
insert into symptoms(symptom_name) values('behaviour changes');
insert into symptoms(symptom_name) values('difficulty in breathing');
insert into symptoms(symptom_name) values('kidney failure');
insert into symptoms(symptom_name) values('dry cough');
insert into symptoms(symptom_name) values('neck stiffness');
insert into symptoms(symptom_name) values('opisthotonus');
insert into symptoms(symptom_name) values('apathy');
insert into symptoms(symptom_name) values('sniff');
insert into symptoms(symptom_name) values('lymphadenopathy');
insert into symptoms(symptom_name) values('jaundice');
insert into symptoms(symptom_name) values('splenomegaly');
insert into symptoms(symptom_name) values('obstruction');
insert into symptoms(symptom_name) values('mind disorders ane');
insert into symptoms(symptom_name) values('neck pain');
insert into symptoms(symptom_name) values('cor pulmonale');
insert into symptoms(symptom_name) values('pruritus ani');
insert into symptoms(symptom_name) values('rhinitis');
insert into symptoms(symptom_name) values('hepatomegaly');
insert into symptoms(symptom_name) values('thrombocytopenia');
insert into symptoms(symptom_name) values('pulmonary edema');
insert into symptoms(symptom_name) values('tender');
insert into symptoms(symptom_name) values('rectal prolapse');
insert into symptoms(symptom_name) values('eosinophilia');
insert into symptoms(symptom_name) values('laryngeal edema');
insert into symptoms(symptom_name) values('anal fissure');
insert into symptoms(symptom_name) values('pulsus paradox');
insert into symptoms(symptom_name) values('night sweat');
insert into symptoms(symptom_name) values('abscess');
insert into symptoms(symptom_name) values('leukopenia');
insert into symptoms(symptom_name) values('chest pains');
insert into symptoms(symptom_name) values('circulatory shock');
insert into symptoms(symptom_name) values('high fever');
insert into symptoms(symptom_name) values('Accidental weight loss');
insert into symptoms(symptom_name) values('urticaria');
insert into symptoms(symptom_name) values('dehydration');
insert into symptoms(symptom_name) values('hypotension');
insert into symptoms(symptom_name) values('photophobia');
insert into symptoms(symptom_name) values('nasal obstruction');
insert into symptoms(symptom_name) values('low blood pressure');
insert into symptoms(symptom_name) values('dysphagia');
insert into symptoms(symptom_name) values('urinating pain');
insert into symptoms(symptom_name) values('cramps');
insert into symptoms(symptom_name) values('arthralgia');

